image: qwe1/docker-pelican

pages:
  stage: deploy
  script:
  - make publish
  artifacts:
    paths:
    - public/
  only:
  - master

test:
  stage: test
  script:
  - make publish
  only:
  - branches
  except:
  - master
