image: python:3.7-stretch

pages:
  stage: deploy
  script:
  - apt-get update && apt-get install -y make
  - pip install -r requirements.txt
  - make publish
  artifacts:
    paths:
    - public/
  only:
  - master

test:
  stage: test
  script:
  - apt-get update && apt-get install -y make
  - pip install -r requirements.txt
  - make publish
  only:
  - branches
  except:
  - master
