---
# .travis.yml

# build using Python 3.6
language: python
python:
  - 3.7
# Cache Dependencies
cache: pip
# we need two Linux packages for the optimize_images plugin
addons:
  apt:
    packages:
    - make

# install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
# build our blog
script:
  - make publish

# deploy to GitHub pages
deploy:
  provider: pages
  local_dir: ./public/
  target-branch: master
  # Make sure you have skip_cleanup set to true,
  # otherwise Travis CI will delete all the files created during the build, which will probably delete what you are trying to upload.
  skip_cleanup: true
  # create the token here
  # https://github.com/settings/tokens/new
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  # only deploy on "main" branch
  on:
    branch: master